<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Pixario.Ingest.Worker-2bda0288-42ea-4dda-b7b3-a6ad7a3029fb</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.12"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Pixario.Ingest.Infrastructure\Pixario.Ingest.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
</Project>
