// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pixario.Ingest.Infrastructure.Persistence;

#nullable disable

namespace Pixario.Ingest.Infrastructure.Migrations
{
    [DbContext(typeof(IngestDbContext))]
    [Migration("20260416115331_JobFailedReason")]
    partial class JobFailedReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pixario.Ingest.Infrastructure.Persistence.Models.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("StoredFileName")
                        .HasColumnType("char(36)")
                        .HasColumnName("stored_file_name");

                    b.HasKey("Id");

                    b.ToTable("image_assets", (string)null);
                });

            modelBuilder.Entity("Pixario.Ingest.Infrastructure.Persistence.Models.ImageRetouchBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("retouch_batch", (string)null);
                });

            modelBuilder.Entity("Pixario.Ingest.Infrastructure.Persistence.Models.ImageRetouchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("image_id");

                    b.Property<string>("JobFailedReason")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("job_failed_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("retouch_jobs", (string)null);
                });

            modelBuilder.Entity("Pixario.Ingest.Infrastructure.Persistence.Models.LogLevelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("log_level");

                    b.HasKey("Id");

                    b.HasIndex("LogLevel")
                        .IsUnique();

                    b.ToTable("log_levels", (string)null);
                });

            modelBuilder.Entity("Pixario.Ingest.Infrastructure.Persistence.Models.ImageRetouchJob", b =>
                {
                    b.HasOne("Pixario.Ingest.Infrastructure.Persistence.Models.ImageRetouchBatch", null)
                        .WithMany("Jobs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pixario.Ingest.Infrastructure.Persistence.Models.ImageAsset", "Image")
                        .WithOne()
                        .HasForeignKey("Pixario.Ingest.Infrastructure.Persistence.Models.ImageRetouchJob", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Pixario.Ingest.Infrastructure.Persistence.Models.ImageRetouchBatch", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
