// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pixario.Ingest.Infrastructure.Persistence;

#nullable disable

namespace Pixario.Ingest.Infrastructure.Migrations
{
    [DbContext(typeof(IngestDbContext))]
    [Migration("20260401225923_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pixario.Ingest.Core.Entities.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("batch_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("storage_path");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("image_assets", (string)null);
                });

            modelBuilder.Entity("Pixario.Ingest.Core.Entities.ImageRetouchBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("retouch_batch", (string)null);
                });

            modelBuilder.Entity("Pixario.Ingest.Core.Entities.ImageRetouchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("retouch_jobs", (string)null);
                });

            modelBuilder.Entity("Pixario.Ingest.Core.Entities.ImageAsset", b =>
                {
                    b.HasOne("Pixario.Ingest.Core.Entities.ImageRetouchBatch", null)
                        .WithMany("Images")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pixario.Ingest.Core.Entities.ImageRetouchJob", b =>
                {
                    b.HasOne("Pixario.Ingest.Core.Entities.ImageRetouchBatch", null)
                        .WithMany("Jobs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pixario.Ingest.Core.Entities.ImageAsset", "Image")
                        .WithOne()
                        .HasForeignKey("Pixario.Ingest.Core.Entities.ImageRetouchJob", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Pixario.Ingest.Core.Entities.ImageRetouchBatch", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
